Jenkinsfile
README.md
src/main/scala/com/cognite/spark/datasource/AssetsRelation.scala
src/main/scala/com/cognite/spark/datasource/CdpConnector.scala
src/main/scala/com/cognite/spark/datasource/Constants.scala
src/main/scala/com/cognite/spark/datasource/DataPointsRelation.scala
src/main/scala/com/cognite/spark/datasource/DefaultSource.scala
src/main/scala/com/cognite/spark/datasource/EventsRelation.scala
src/main/scala/com/cognite/spark/datasource/FilesRelation.scala
src/main/scala/com/cognite/spark/datasource/RawTableRelation.scala
src/main/scala/com/cognite/spark/datasource/ThreeDModelRevisionMappingsRelation.scala
src/main/scala/com/cognite/spark/datasource/ThreeDModelRevisionNodesRelation.scala
src/main/scala/com/cognite/spark/datasource/ThreeDModelRevisionSectorsRelation.scala
src/main/scala/com/cognite/spark/datasource/ThreeDModelRevisionsRelation.scala
src/main/scala/com/cognite/spark/datasource/ThreeDModelsRelation.scala
src/main/scala/com/cognite/spark/datasource/TimeSeriesRelation.scala
src/test/scala/com/cognite/spark/datasource/BaseUrlTest.scala
src/test/scala/com/cognite/spark/datasource/BasicUseTest.scala
src/test/scala/com/cognite/spark/datasource/SparkTest.scala
src/test/scala/com/cognite/spark/datasource/URLTest.scala

Refactor code to let users specify other base URLs than
api.cognitedata.com, such as greenfield.cognitedata.com.

Allow base URL to be configured

---

build.sbt

To fix issues where the consumer of the library get errors about 'macroSub' not found.
Based on https://www.scala-sbt.org/1.0/docs/Macro-Projects.html#Distribution
Commited with @Tapped

Only depend on macroSub internally

---

src/main/scala/com/cognite/spark/datasource/AssetsRelation.scala
src/main/scala/com/cognite/spark/datasource/CdpRelation.scala
src/main/scala/com/cognite/spark/datasource/EventsRelation.scala
src/main/scala/com/cognite/spark/datasource/TimeSeriesRelation.scala
src/test/scala/com/cognite/spark/datasource/BasicUseTest.scala

Add some fields from data sources that have been left out. Events used
0.5 for updates, that had to be upgraded to 0.6 to allow for more fields,
which also gave need for the UpdateEventItem.

Include all fields from API

---

src/main/scala/com/cognite/spark/datasource/MetricsSource.scala

AppId is appended by default by Spark.

Remove appId from sourceName

---

src/main/scala/com/cognite/spark/datasource/EventsRelation.scala
src/main/scala/com/cognite/spark/datasource/TimeSeriesRelation.scala

Error messages for upserts now display the error message from the API.
Also, changed the update from a PUT to a POST.

Fix error messages for upserts

---

src/main/scala/com/cognite/spark/datasource/AssetsRelation.scala
src/main/scala/com/cognite/spark/datasource/CdpRelation.scala
src/main/scala/com/cognite/spark/datasource/DataPointsRelation.scala
src/main/scala/com/cognite/spark/datasource/EventsRelation.scala
src/main/scala/com/cognite/spark/datasource/MetricsSource.scala
src/main/scala/com/cognite/spark/datasource/NumericDataPointsRelation.scala
src/main/scala/com/cognite/spark/datasource/RawTableRelation.scala
src/main/scala/com/cognite/spark/datasource/StringDataPointsRelation.scala
src/main/scala/com/cognite/spark/datasource/TimeSeriesRelation.scala

Previously when Jetfire was using the new metrics in cdp-spark-datasource, we get errors about registering metrics that already exist, possibly due to Spark creating multiple instances of <DataType>Relation classes (and thus multiple instances of MetricSource)for read and for write.
This fix makes MetricSources a global singleton, so all metrics of all jobs are put into one hashmap. They are later removed when job is finished. This should be thread-safe.

Fix bug of same metric registered multiple times

---

src/main/scala/com/cognite/spark/datasource/CdpRelation.scala
src/main/scala/com/cognite/spark/datasource/DefaultSource.scala
src/main/scala/com/cognite/spark/datasource/EventsRelation.scala
src/main/scala/com/cognite/spark/datasource/TimeSeriesRelation.scala
src/test/scala/com/cognite/spark/datasource/CdpRddTest.scala
src/test/scala/com/cognite/spark/datasource/DataPointsRelationTest.scala
src/test/scala/com/cognite/spark/datasource/EventsRelationTest.scala
src/test/scala/com/cognite/spark/datasource/StringDataPointsRelationTest.scala
src/test/scala/com/cognite/spark/datasource/TimeSeriesUpsertTest.scala
src/test/scala/com/cognite/spark/datasource/URLTest.scala

Work in progress, based on Emil's work in #142 and #117.
Implemented three different save modes: write, upsert and update, provided as .option("savemode", "upsert"). Could help users avoid making errors, what do you think?
Declaring EventsInsertion inside EventsRelation is temporary, we should probably extract common methods in a superclass or similar.

Add support for writing in save mode

---

src/main/scala/com/cognite/spark/datasource/AssetsRelation.scala
src/main/scala/com/cognite/spark/datasource/CdpConnector.scala
src/main/scala/com/cognite/spark/datasource/CdpRdd.scala
src/main/scala/com/cognite/spark/datasource/CursorsCursorIterator.scala
src/main/scala/com/cognite/spark/datasource/DataPointsRelation.scala
src/main/scala/com/cognite/spark/datasource/DefaultSource.scala
src/main/scala/com/cognite/spark/datasource/EventsRelation.scala
src/main/scala/com/cognite/spark/datasource/FilesRelation.scala
src/main/scala/com/cognite/spark/datasource/NextCursorIterator.scala
src/main/scala/com/cognite/spark/datasource/NumericDataPointsRdd.scala
src/main/scala/com/cognite/spark/datasource/RawTableRelation.scala
src/main/scala/com/cognite/spark/datasource/StringDataPointsRdd.scala
src/main/scala/com/cognite/spark/datasource/TimeSeriesRelation.scala
src/main/scala/com/cognite/spark/datasource/cdpAuth.scala
src/test/scala/com/cognite/spark/datasource/AssetsRelationTest.scala
src/test/scala/com/cognite/spark/datasource/CdpRddTest.scala
src/test/scala/com/cognite/spark/datasource/EventsRelationTest.scala
src/test/scala/com/cognite/spark/datasource/SparkTest.scala
src/test/scala/com/cognite/spark/datasource/ThreeDModelRevisionMappingsRelationTest.scala
src/test/scala/com/cognite/spark/datasource/ThreeDModelRevisionNodesRelationTest.scala
src/test/scala/com/cognite/spark/datasource/ThreeDModelRevisionSectorsRelationTest.scala
src/test/scala/com/cognite/spark/datasource/ThreeDModelRevisionsRelationTest.scala
src/test/scala/com/cognite/spark/datasource/TimeSeriesUpsertTest.scala
src/test/scala/com/cognite/spark/datasource/URLTest.scala

This makes it possible to use the spark datasource in cituations where
an api-key is unavailable, but instead a bearer token is.

Add bearer token support

---

src/test/scala/com/cognite/spark/datasource/AssetsRelationTest.scala
src/test/scala/com/cognite/spark/datasource/FilesRelationTest.scala

This fixes the failing test from FilesRelation, and uses collect in AssetsRelationTest for consistency. We should also find a way to fix TimeSeriesRelationTest, which has two main problems:
- should successfully both update and insert time series
This test times out sometimes
- should support abort in savemode
This sometimes fails because it doesn't always get a conflict on inserting existing rows due to EC.
Any other tests we know of that fail? The `does not throw exception` should be fixed everywhere we use the pattern, and since we'll add more of it once we implement savemode for other resource types it will be an even bigger problem soon.

Fix tests failing because of eventual consistency

---

macro/src/main/scala/SparkSchemaHelper.scala
src/main/scala/com/cognite/spark/datasource/AssetsRelation.scala
src/main/scala/com/cognite/spark/datasource/CdpConnector.scala
src/main/scala/com/cognite/spark/datasource/CdpRelation.scala
src/main/scala/com/cognite/spark/datasource/DefaultSource.scala
src/main/scala/com/cognite/spark/datasource/EventsRelation.scala
src/main/scala/com/cognite/spark/datasource/TimeSeriesRelation.scala
src/main/scripts/Pipfile
src/main/scripts/Pipfile.lock
src/test/scala/com/cognite/spark/datasource/AssetsRelationTest.scala
src/test/scala/com/cognite/spark/datasource/DataPointsRelationTest.scala
src/test/scala/com/cognite/spark/datasource/EventsRelationTest.scala
src/test/scala/com/cognite/spark/datasource/TimeSeriesUpsertTest.scala

@Tapped I couldn't make `val column = q"${typeOf[Try[_]]}(Option($r.getAs[$rowType]($name))).toOption.flatten"` work, so importing Try everywhere.
```
/cdp-spark-datasource/src/main/scala/com/cognite/spark/datasource/TimeSeriesRelation.scala:
121:53: scala.util.Try[_$5] does not take parameters
val timeSeriesItem = fromRow[TimeSeriesItem](r)
^
```

Add support for partial updates

---

src/main/scala/com/cognite/spark/datasource/DefaultSource.scala

Fix it by removing it, since it turns into "Resource type &apos;assets does not support save()" in Databricks output and we don't really need it.

Fix unclosed quote in error message

---

src/main/scala/com/cognite/spark/datasource/EventsRelation.scala
src/main/scala/com/cognite/spark/datasource/TimeSeriesRelation.scala
src/test/scala/com/cognite/spark/datasource/EventsRelationTest.scala
src/test/scala/com/cognite/spark/datasource/FilesRelationTest.scala
src/test/scala/com/cognite/spark/datasource/TimeSeriesRelationTest.scala

Make sure we don't send values with null ids to the API on update.
Instead check and throw an IllegalArgumentException if we receive
any null ids on update. Previously we only checked this on assets, but now we also check on timeSeries and events.

Check for null id on update

---

src/main/scala/com/cognite/spark/datasource/CdpRdd.scala
src/main/scala/com/cognite/spark/datasource/CdpRelation.scala
src/main/scala/com/cognite/spark/datasource/EventsRelation.scala
src/main/scala/com/cognite/spark/datasource/FilesRelation.scala
src/main/scala/com/cognite/spark/datasource/RawTableRelation.scala
src/test/scala/com/cognite/spark/datasource/CdpRddTest.scala
src/test/scala/com/cognite/spark/datasource/EventsRelationTest.scala

Implement pushdown filters for type, subtype, assetIds, startTime and
source. ID will have to be handled in another way, since ID-filters are
passed in the body rather than as query parameters.

Implement pushdown filters on Events

---

src/main/scala/com/cognite/spark/datasource/AssetsRelation.scala
src/main/scala/com/cognite/spark/datasource/EventsRelation.scala
src/main/scala/com/cognite/spark/datasource/TimeSeriesRelation.scala
src/test/scala/com/cognite/spark/datasource/AssetsRelationTest.scala
src/test/scala/com/cognite/spark/datasource/EventsRelationTest.scala
src/test/scala/com/cognite/spark/datasource/TimeSeriesRelationTest.scala

This was already done for insertInto, but is now done for all ways of
writing to CDF.

Remove metadata keys with null values

---

build.sbt
macro/src/main/scala/SparkSchemaHelper.scala
src/main/scala/com/cognite/spark/datasource/AssetsRelationV1.scala
src/main/scala/com/cognite/spark/datasource/CdpConnector.scala
src/main/scala/com/cognite/spark/datasource/DefaultSource.scala
src/main/scala/com/cognite/spark/datasource/EventsRelationV1.scala
src/main/scala/com/cognite/spark/datasource/FilesRelation.scala
src/main/scala/com/cognite/spark/datasource/SdkV1Relation.scala
src/main/scala/com/cognite/spark/datasource/TimeSeriesRelation.scala
src/test/scala/com/cognite/spark/datasource/AssetsRelationTest.scala
src/test/scala/com/cognite/spark/datasource/BaseUrlTest.scala
src/test/scala/com/cognite/spark/datasource/DataPointsRelationTest.scala
src/test/scala/com/cognite/spark/datasource/EventsRelationTest.scala
src/test/scala/com/cognite/spark/datasource/StringDataPointsRelationTest.scala
src/test/scala/com/cognite/spark/datasource/TimeSeriesRelationTest.scala

Well aware this is wrecking the test coverage, but that'll change when we remove the old files (`CdpRelation`, `CdpRdd`, `EventsRelation`, `AssetsRelation`). At least for Assets I think we should make a way to use the old version, since Asset types won't be in `v1` for a while. EventsRelation could be deleted, but pushdown filters aren't ready in EventsRelationV1 yet, so we could make `0.6` avilable here too.

Rewrite events to use V1

---

README.md

The dependency on the Cognite version of spark-metrics was removed in February.

Remove outdated info about spark-metrics

---

src/main/scala/cognite/spark/SdkV1Rdd.scala
src/test/scala/cognite/spark/SdkV1RddTest.scala
src/test/scala/cognite/spark/TimeSeriesRelationTest.scala

- Pass on errors and exceptions thrown by CDF streams
- The set handling duplicates when pushdown filters have overlap is now
threadsafe

Expose errors in reads

---

src/main/scala/cognite/spark/v1/Constants.scala
src/main/scala/cognite/spark/v1/PushdownUtilities.scala
src/test/scala/cognite/spark/v1/DataPointsRelationTest.scala

The default for the upper timestamp filter on datapoints was too high,
this is now reduced to year 2100.

Reduce default maximum timestamp

---

Jenkinsfile
src/main/scala/cognite/spark/v1/EventsRelation.scala
src/main/scala/cognite/spark/v1/PushdownUtilities.scala
src/test/scala/cognite/spark/v1/AssetsRelationTest.scala
src/test/scala/cognite/spark/v1/DataPointsRelationTest.scala
src/test/scala/cognite/spark/v1/EventsRelationTest.scala
src/test/scala/cognite/spark/v1/SdkV1RddTest.scala
src/test/scala/cognite/spark/v1/SparkTest.scala
src/test/scala/cognite/spark/v1/StringDataPointsRelationTest.scala
src/test/scala/cognite/spark/v1/ThreeDModelRevisionMappingsRelationTest.scala
src/test/scala/cognite/spark/v1/ThreeDModelRevisionNodesRelationTest.scala
src/test/scala/cognite/spark/v1/ThreeDModelRevisionsRelationTest.scala
src/test/scala/cognite/spark/v1/TimeSeriesRelationTest.scala
src/test/scala/cognite/spark/v1/URLTest.scala

Having all tests write and delete data based on the same unit turned out to be a bad idea, since this increases the number of operations that happen on the same data. This PR decouples the tests, which should fix a lot of the flaky behavior we're seeing now.

Fix flaky tests

---

src/main/scala/cognite/spark/v1/AssetsRelation.scala
src/main/scala/cognite/spark/v1/CdpConnector.scala
src/main/scala/cognite/spark/v1/DataPointsRelation.scala
src/main/scala/cognite/spark/v1/DefaultSource.scala
src/main/scala/cognite/spark/v1/EventsRelation.scala
src/main/scala/cognite/spark/v1/NumericDataPointsRdd.scala
src/main/scala/cognite/spark/v1/RawTableRelation.scala
src/main/scala/cognite/spark/v1/SdkV1Relation.scala
src/main/scala/cognite/spark/v1/TimeSeriesRelation.scala

Spark uses the global execution context for a lot of things, and depleting it gives some horrendous error messages and breaks the reporting of the original exception back to the driver.
So don't use it.

Avoid global execution context

---

src/main/scala/cognite/spark/v1/AssetsRelation.scala
src/main/scala/cognite/spark/v1/DefaultSource.scala
src/main/scala/cognite/spark/v1/EventsRelation.scala
src/main/scala/cognite/spark/v1/NumericDataPointsRelation.scala
src/main/scala/cognite/spark/v1/SdkV1Relation.scala
src/main/scala/cognite/spark/v1/StringDataPointsRelation.scala
src/main/scala/cognite/spark/v1/TimeSeriesRelation.scala

-- datapoints and stringdatapoints only support upserts (deleted the part about deletes bc we are not sure how it will look in jetfire for now)

Save mode for numeric and string datapoints

---

README.md
src/main/scala/cognite/spark/v1/EventsRelation.scala
src/main/scala/cognite/spark/v1/PushdownUtilities.scala
src/test/scala/cognite/spark/v1/EventsRelationTest.scala

Push down filters were not applied when filtering on a push down column *and* a not push down column. Also sneaking in the pushdown filters on `createdTime` and `lastUpdatedTime` for Events, and an update to the Readme.md.

[DT-1115] Fix bug in push down implementation

---

src/main/scala/cognite/spark/v1/AssetsRelation.scala
src/main/scala/cognite/spark/v1/DefaultSource.scala
src/main/scala/cognite/spark/v1/EventsRelation.scala
src/main/scala/cognite/spark/v1/SdkV1Relation.scala
src/test/scala/cognite/spark/v1/AssetsRelationTest.scala
src/test/scala/cognite/spark/v1/EventsRelationTest.scala
src/test/scala/cognite/spark/v1/SparkTest.scala

- support ignoreUnknownIds when doing delete
- user can specify `true as ignoreUnknownIds` in delete queries to not error out when encountering unknown ids
- `false as ignoreUnknownIds` or not specifying any value for ignoreUnknownIds will error out when encountering unknown ids

Support ignoreUnknownIds for asset and event deletes

---

src/main/scala/cognite/spark/v1/NumericDataPointsRdd.scala

Since aggregates are not returned unless there are enough datapoints to
fill the range, we now add an additional range at the end when reading
datapoints without aggregates.

[DT-1218] Add padding range to datapoints query

---

src/main/scala/cognite/spark/v1/CdpConnector.scala

Even if we try to limit the number of concurrent requests using `.grouped(Constants.MaxConcurrentRequests)` it's not perfect, and it's possible to run out of ephemeral ports used by Netty if we don't limit this thread pool.

Limit the CdpConnector thread pool to MaxConcurrentRequests

---

src/test/scala/cognite/spark/v1/AssetsHierarchyBuilderTest.scala

Some tests had an extra comma after the last item of a Sequence, which
is fine in Scala 2.12, but stopped compilation for 2.11 on master.

Fix test errors only seen in Scala 2.11

---

src/test/scala/cognite/spark/v1/AssetHierarchyBuilderTest.scala

We only compile/test on Scala 2.12 for PR builds, so we didn't catch
this change that was not compatible with Scala 2.11.

Remove trailing comma

---

src/main/scala/cognite/spark/v1/RawTableRelation.scala
src/test/scala/cognite/spark/v1/RawTableRelationTest.scala

Before we ended up reading 200 (numPartitions) * 10000 (defaultInferenceLimit) just to infer schema. This PR sets num partitions to 1 during schema inference.
I don't think we've a good way of testing this unfortunately.

[DT-1424] Only infer schema on a small subset of the table

---

src/test/scala/cognite/spark/v1/EventsRelationTest.scala

API is at the moment struggling with Event consistency, so we should temporarily ignore the events test so that we can make a release.

Ignore events test since backend is struggling

---

performancebench/src/main/scala/cognite/spark/performancebench/EventPerformance.scala
performancebench/src/main/scala/cognite/spark/performancebench/Main.scala
src/main/scala/cognite/spark/v1/CdpConnector.scala
src/main/scala/cognite/spark/v1/Constants.scala
src/main/scala/cognite/spark/v1/DataPointsRelation.scala
src/main/scala/cognite/spark/v1/DefaultSource.scala
src/main/scala/cognite/spark/v1/RawTableRelation.scala
src/main/scala/cognite/spark/v1/SdkV1Relation.scala
src/main/scala/cognite/spark/v1/SttpClientBackendFactory.scala

SyncQueue doesn't queue the Runnables in a queue collection, but instead queues the runnable for an available thread, or if no threads are available it will create a thread. However, if max number of threads is reached, it'll throw. I propose using a fixed thread pool instead based on the number of CPUs available.
I don't see why this needs to be related to max concurrent requests, as this thread pool is not used for the actual request. It's only used for scheduling a request. It could probably be smaller as well, as it shouldn't take long to schedule.

Threadpool related fixes

---

performancebench/src/main/scala/cognite/spark/performancebench/Main.scala
performancebench/src/main/scala/cognite/spark/performancebench/Warmup.scala

Read some events to warmup the Spark cluster, since without warmup, we get biased metric results.

Add warmup logic to perf. bench

---

README.md
src/main/scala/cognite/spark/v1/AssetHierarchyBuilder.scala
src/main/scala/cognite/spark/v1/DefaultSource.scala
src/test/scala/cognite/spark/v1/AssetHierarchyBuilderTest.scala
src/test/scala/cognite/spark/v1/SparkTest.scala

Add support for inserting subtrees (i.e. nodes rooted outside of the inserted tree) and multiple trees at once.
The builder now works like this:
* Group the input data into a set of trees (connected components)
- and validate that it does not contain cycle. Note that previously cycles were allowed when `ignoreDisconnectedAssets` was set
* If `allowSubtreeIngestion` is `false`
- drop trees without root when if `ignoreDisconnectedAssets` is set
- otherwise raise an error
* If `allowMultipleRoots`, check that there is only one tree
* Empty insertions are now allowed (this will quite certainly if you are doing incremental updates). Only when the input set was non-empty and all nodes were dropped, the error is raised.
* Check that all subtree have an existing parent.
* The trees are inserted …

[DT-1371][DT-1373] Asset Hierarchy generalization

---

Jenkinsfile
src/test/scala/cognite/spark/v1/AssetHierarchyBuilderTest.scala

And change the Jenkinsfile to prevent this from happening again.

Scala 2.11 fixes for AssetHierarchyBuilderTest

---

macro/src/main/scala/SparkSchemaHelper.scala
src/test/scala/cognite/spark/v1/AssetHierarchyBuilderTest.scala
src/test/scala/cognite/spark/v1/AssetsRelationTest.scala
src/test/scala/cognite/spark/v1/DataPointsRelationTest.scala
src/test/scala/cognite/spark/v1/EventsRelationTest.scala
src/test/scala/cognite/spark/v1/SparkTest.scala
src/test/scala/cognite/spark/v1/TimeSeriesRelationTest.scala
src/test/scala/cognite/spark/v1/URLTest.scala

We now explicitly handle the case when the column has an unexpected type.
We also do implicit conversions to Double and Long from other numeric types.
Minor improvements: shorter type names, hint for parentExternalId=NULL

[DT-1127] Improve error message for column incorrect type

---

macro/src/main/scala/SparkSchemaHelper.scala
src/main/scala/cognite/spark/v1/AssetsRelation.scala
src/main/scala/cognite/spark/v1/CdpConnector.scala
src/main/scala/cognite/spark/v1/EventsRelation.scala
src/main/scala/cognite/spark/v1/FilesRelation.scala
src/main/scala/cognite/spark/v1/SparkSchemaHelperRuntime.scala
src/main/scala/cognite/spark/v1/TimeSeriesRelation.scala
src/test/scala/cognite/spark/v1/AssetHierarchyBuilderTest.scala
src/test/scala/cognite/spark/v1/DataPointsRelationTest.scala
src/test/scala/cognite/spark/v1/SparkSchemaHelperTest.scala

the `fromRow` macro now checks that `Map[String, String]` contains only strings, ignores null values and trims the values to the metadata size limit.

[CDF-5654] Check Map[String, String] (a metadata field) in fromRow

---

README.md

this breaks on our docs portal as well

docs(readme): escape special character

---

macro/src/main/scala/SparkSchemaHelper.scala
src/test/scala/cognite/spark/v1/EventsRelationTest.scala
src/test/scala/cognite/spark/v1/SparkSchemaHelperTest.scala

Spark uses `java.math.BigInteger` and `java.math.BigDecimal` instead of the Scala types, so the implicit conversions actually did not work.

Fix implicit conversion from BigInteger/BigDecimal

---

README.md
src/main/scala/cognite/spark/v1/DataPointsRelation.scala
src/main/scala/cognite/spark/v1/NumericDataPointsRelation.scala
src/main/scala/cognite/spark/v1/StringDataPointsRelation.scala
src/test/scala/cognite/spark/v1/DataPointsRelationTest.scala
src/test/scala/cognite/spark/v1/StringDataPointsRelationTest.scala

This is the delete schema for datapoints delete:
```scala
final case class DeleteDataPointsItem(
id: Option[Long],
externalId: Option[String],
exclusiveBegin: Option[Instant],
inclusiveBegin: Option[Instant],
exclusiveEnd: Option[Instant],
inclusiveEnd: Option[Instant]
)
```
Can delete ranges. If you want to delete specific points, just set `inclusiveBegin` and `inclusiveEnd` to the same value.
TODO:

[CDF-5528] Add delete for data points

---

performancebench/src/main/scala/cognite/spark/performancebench/SparkUtil.scala
src/main/scala/cognite/spark/v1/AssetHierarchyBuilder.scala
src/main/scala/cognite/spark/v1/AssetsRelation.scala
src/main/scala/cognite/spark/v1/CDFSparkException.scala
src/main/scala/cognite/spark/v1/DataPointsRelation.scala
src/main/scala/cognite/spark/v1/DefaultSource.scala
src/main/scala/cognite/spark/v1/FilesRelation.scala
src/main/scala/cognite/spark/v1/NumericDataPointsRdd.scala
src/main/scala/cognite/spark/v1/NumericDataPointsRelation.scala
src/main/scala/cognite/spark/v1/PushdownUtilities.scala
src/main/scala/cognite/spark/v1/RawTableRelation.scala
src/main/scala/cognite/spark/v1/SdkV1Relation.scala
src/main/scala/cognite/spark/v1/SequenceRowsRelation.scala
src/main/scala/cognite/spark/v1/SequencesRelation.scala
src/main/scala/cognite/spark/v1/SparkSchemaHelperRuntime.scala
src/main/scala/cognite/spark/v1/StringDataPointsRelation.scala
src/main/scala/cognite/spark/v1/TimeSeriesRelation.scala
src/test/scala/cognite/spark/v1/AssetHierarchyBuilderTest.scala
src/test/scala/cognite/spark/v1/AssetsRelationTest.scala
src/test/scala/cognite/spark/v1/DataPointsRelationTest.scala
src/test/scala/cognite/spark/v1/RawTableRelationTest.scala
src/test/scala/cognite/spark/v1/SparkSchemaHelperTest.scala
src/test/scala/cognite/spark/v1/TimeSeriesRelationTest.scala
src/test/scala/cognite/spark/v1/URLTest.scala

Exceptions in Spark must have common base class so that we can decide which to let through in Jetfire. https://cognitedata.atlassian.net/secure/RapidBoard.jspa?rapidView=303&modal=detail&selectedIssue=CDF-5649

Add exception base classes and use custom exceptions

---

src/main/scala/cognite/spark/jackson/RowSerializer.scala
src/main/scala/cognite/spark/jackson/SparkModule.scala
src/main/scala/cognite/spark/v1/RawTableRelation.scala
src/test/scala/cognite/spark/jackson/SparkModuleTest.scala
src/test/scala/cognite/spark/v1/FunctionsUDFTest.scala
src/test/scala/cognite/spark/v1/RawTableRelationTest.scala

By default, Row objects (which is how structs are represented in Spark SQL) are serialized as:
```json
{ "values": ["myValue"], "schema": [{ "name": "myFieldName", ... }] }
```
This is not what we want when inserting to RAW, so let's implement a custom serializer which produces objects like this instead:
```json
{ "myFieldName": "myValue" }
```

[CDF-8392] Serialize struct values as plain JSON objects

---

build.sbt
src/main/scala/cognite/spark/v1/CdpConnector.scala
src/main/scala/cognite/spark/v1/DefaultSource.scala
src/test/scala/cognite/spark/v1/SparkTest.scala

Let the new sdk version set `x-cdp-sdk`, let `x-cdp-app` remain as `com.cognite.spark.datasource-VERSION`, and let user (optionally) set `x-cdp-clienttag` in options.

Set x-cdp headers correcly

---

CHANGELOG.md
src/main/scala/cognite/spark/v1/RawTableRelation.scala

This makes the default RAW schema accessible without requiring an instance of RawTableRelation.
This is so that we can use it as the source of truth when querying RAW from Jetfire without schema inference, instead of copypasting the schema into the Jetfire codebase.

Move RawTableRelation.defaultSchema to companion object

---

.github/workflows/main.yaml
build.sbt
src/main/scala/cognite/spark/v1/AssetsRelation.scala
src/main/scala/cognite/spark/v1/Constants.scala
src/main/scala/cognite/spark/v1/SdkV1Relation.scala
src/test/scala/cognite/spark/v1/AssetsRelationTest.scala

Turns out we were doing single partitions everywhere by default. Was this implemented to avoid anything in particular? We could do this change in jetfire-backend instead, but is this ever good at 1 * 1 anyways?

Increase the default number of partitions

---

CHANGELOG.md
build.sbt
src/main/scala/cognite/spark/v1/AssetHierarchyBuilder.scala
src/main/scala/cognite/spark/v1/AssetsRelation.scala

**Ready for review**
Tests for Assets and AssetHierarchy are successful and I tried update/upsert with labels for both of them in spark-shell and jetfire. 
Needs: https://github.com/cognitedata/cognite-sdk-scala/pull/289

Add labels for asset updates.

---

build.sbt
src/test/scala/cognite/spark/v1/OAuth2Test.scala

In order to add OidcTokenAuth to jetfire, didn't catch any code change need here.

Bump scala sdk version

---

src/main/scala/cognite/spark/v1/AssetHierarchyBuilder.scala
src/main/scala/cognite/spark/v1/DefaultSource.scala
src/test/scala/cognite/spark/v1/AssetHierarchyBuilderTest.scala
src/test/scala/cognite/spark/v1/SparkTest.scala

this fixes part of the problem that we fired at least 3 request
for each subtree, which was a lot for flat hierarchies
This patch is not complete fix of the problem as it does not batch fetching of
existing subtrees
It changes the behavior of AsserHierarchyBuilder slightly:
* assets.created metric is not even created when no asset is created. This is
consistent with how the other metrics work.
* error message of moving asset between subtrees also includes externalId of
the subtree root. No information is missing compared to previous version.

asset hierarchy: batch mutiple subtrees together 

---

CHANGELOG.md
src/main/scala/cognite/spark/v1/DefaultSource.scala

While debugging other issue in Jetfire, I run into this limitation.

Fix batchSize for deleting datapoints

---

src/main/scala/cognite/spark/v1/AssetHierarchyBuilder.scala
src/test/scala/cognite/spark/v1/AssetHierarchyBuilderTest.scala

This will make the AssetHierarchyBuilder actually work for
very flat and large trees, since the number of request will be about
(number of items)/100

asset hierarchy: Batch fetching of existing subtrees

---

CHANGELOG.md
build.sbt
src/main/scala/cognite/spark/v1/DataPointsRelation.scala
src/main/scala/cognite/spark/v1/DefaultSource.scala
src/main/scala/cognite/spark/v1/NumericDataPointsRelation.scala
src/main/scala/cognite/spark/v1/StringDataPointsRelation.scala

Main problem was that when inserting into very many time series,
we converged into making 1 request per datapoint - because
each datapoint for one series ended up in a different partition.
This lead to a surge of parallel requests -> rate limiting -> more problems.
So now we also limit the write parallism in the same way as
we do with read parallism.

Fix performance problem with datapoint insertion

---

src/main/scala/cognite/spark/v1/DataPointsRelation.scala
src/main/scala/cognite/spark/v1/NumericDataPointsRdd.scala
src/main/scala/cognite/spark/v1/StringDataPointsRelation.scala

Surprisingly, this scala lalalalala improves performance quite
a bit. What took 102 seconds now takes just 50 (and it's
now limited by my network instead of the CPU).
The problem was that we were appending quite big Seq together, which was pretty slow.
fs2 does lot of things to avoid this, so that's why it's faster.

Use fs2.Pull for datapoints

---

src/main/scala/cognite/spark/v1/PushdownUtilities.scala
src/test/scala/cognite/spark/v1/AssetsRelationTest.scala

First I thought about raing some nicer error, but it's easier
to just ignore nulls in the array. It's also more convenient for
some use cases - users sometimes have a label column
in their raw table that is nullable  and then want to do `array(label)` in SQL

Don't crash on NULL in labels

---

src/test/scala/cognite/spark/v1/RawTableRelationTest.scala
src/test/scala/cognite/spark/v1/SparkTest.scala

Turns out it doesnt crash it here, so the error must be in jetfire.

Add a test covering that this infamous query does not crash Spark

---

src/main/scala/cognite/spark/v1/DataPointsRelation.scala
src/main/scala/cognite/spark/v1/DefaultSource.scala
src/test/scala/cognite/spark/v1/RelationshipsRelationTest.scala
src/test/scala/cognite/spark/v1/SparkTest.scala

The only thing limiting number of write requests when
the dataset was large was the RateLimitingBackend's.
However, that's not very strict, and more importantly
scales with the number of Spark partitions. So when the
user had many partitions, we would allow basically
infinitely many parallel requests.
This PR limits the write parallelism in the same way as
we limit read paralelism - capped by config.partitions
(meaning CDF partitions). Also we do a repartition if the
number of Spark partitions is large, compared to CDF
insertion, repartition is fairly cheap and it avoids Jetfire
getting stuck on inserting one large partition, if the
distribution is uneven.

Limit parallelism on write according to settings

---

CHANGELOG.md
src/main/scala/cognite/spark/v1/RawTableRelation.scala

We tried to add it back to fix the 429 Conflict issue, but
it didn't help, so I'm adding this back.
With the table added back, I'm unable to dump some
RAW tables on my laptop.

Remove RAW deduplication table again

---

cdf_dump/README.md
cdf_dump/src/main/scala/cognite/spark/cdfdump/Main.scala
cdf_dump/src/main/scala/cognite/spark/cdfdump/MetricsWatcher.scala
cdf_dump/src/main/scala/cognite/spark/cdfdump/SparkHelper.scala

It also shows throughput which makes it much easier
to compare Spark DS performance across different
RAW tables, for example. Also makes it less frustrating
to wait few minutes when I see that it's crunching
though millions of rows each minute :)
It prints something like this:
```
22/02/25 11:57:22 INFO MetricsWatcher: raw.test.cpu2.rows.read +2.2M (8.7M/min),       requests +364.0 (1.4k/min),       requestsWithoutRetries +336.0 (1.3k/min),       requests.429.response +30.0 (116.0/min)
22/02/25 11:57:37 INFO MetricsWatcher: raw.test.cpu2.rows.read +2.8M (11.0M/min),       requests +278.0 (1.1k/min),       requestsWithoutRetries +267.0 (1.1k/min),       requests.429.response +9.0 (35.0/min)
22/02/25 11:57:52 INFO MetricsWatcher: raw.test.cpu2.rows.read +2.3M (9.3M/min),       requests …
```

Support metrics in cdf_dump

---

CHANGELOG.md
build.sbt
src/main/scala/cognite/spark/v1/CdpConnector.scala
src/main/scala/cognite/spark/v1/StreamIterator.scala
src/test/scala/cognite/spark/v1/SparkTest.scala

Spark is hanging because all the Threads `CDF-Spark-compute` is locked. Stack trace from thread dump in the spark UI
```
java.base@11.0.13/jdk.internal.misc.Unsafe.park(Native Method)
java.base@11.0.13/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
java.base@11.0.13/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
java.base@11.0.13/java.util.concurrent.ArrayBlockingQueue.put(ArrayBlockingQueue.java:367)
cognite.spark.v1.StreamIterator$.$anonfun$enqueueStreamResults$2(StreamIterator.scala:76)
cognite.spark.v1.StreamIterator$$$Lambda$1560/0x0000000840c22440.apply$mcV$sp(Unknown Source)
app//scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18) …
```

Use IO.blocking when dealing with queue in StreamIterator

---

.github/workflows/main.yaml
README.md
build.sbt
src/main/scala/cognite/spark/v1/DataModelInstancesHelper.scala
src/main/scala/cognite/spark/v1/DefaultSource.scala
src/main/scala/cognite/spark/v1/udf/CogniteUdfs.scala
src/test/scala/cognite/spark/v1/AssetsRelationTest.scala
src/test/scala/cognite/spark/v1/DataModelInstancesRelationTest.scala
src/test/scala/cognite/spark/v1/DataPointsRelationTest.scala
src/test/scala/cognite/spark/v1/FilesRelationTest.scala
src/test/scala/cognite/spark/v1/FunctionsUDFTest.scala
src/test/scala/cognite/spark/v1/SdkV1RddTest.scala
src/test/scala/cognite/spark/v1/SparkTest.scala
src/test/scala/cognite/spark/v1/StringDataPointsRelationTest.scala
src/test/scala/cognite/spark/v1/TimeSeriesRelationTest.scala

CDF-17129
Test is added in https://github.com/cognitedata/cognite-sdk-scala/pull/577 but we don't need a new version of SDK since we keep treating Json as a String anyway.
Also doing migration to use OIDC instead of READ_API_KEY for public data.
More ref from https://hub.cognite.com/open-industrial-data-211/openid-connect-on-open-industrial-data-993

Add support for property Json in FDM

---

src/test/scala/cognite/spark/v1/DataPointsRelationTest.scala
src/test/scala/cognite/spark/v1/OAuth2Test.scala

I made some changes to avoid CI failures due to the issue in bluefield: https://cognitedata.slack.com/archives/C6Q390MBJ/p1672937203178239
Now reverting them back

Undo DataPointsRelationTest ignore's

---

build.sbt
src/main/scala/cognite/spark/v1/DefaultSource.scala
src/main/scala/cognite/spark/v1/FlexibleDataModelRelationUtils.scala
src/main/scala/cognite/spark/v1/FlexibleDataModelsRelation.scala
src/test/scala/cognite/spark/v1/FlexibleDataModelsRelationTest.scala
src/test/scala/cognite/spark/v1/RelationshipsRelationTest.scala

- Use multiple filter requests based on View's `usedFor`
- organising tests to avoid accidentally deleting unrelated edge dependencies
- switching to default client instead of alpha

Multiple filter reqeusts for usedFor All

---

src/main/scala/cognite/spark/v1/FlexibleDataModelRelationUtils.scala
src/test/scala/cognite/spark/v1/FlexibleDataModelRelationUtilsTest.scala

- Checking nullability of `Row` fields based on the first `Row` schema seems to be not working in e2e tests
- This works fine in integrations tests
The error `Property [Name] cannot contain null values` is not correct.
That data column is `null` free

Remove first row schema based nullability check

---

build.sbt
src/main/scala/cognite/spark/v1/wdl/WellDataLayerRelation.scala
src/test/scala/cognite/spark/v1/wdl/TestWdlClient.scala
src/test/scala/cognite/spark/v1/wdl/WDLWellSourcesTest.scala

- Transformations writing to the well data layer didn't update the `itemsCreated` metric.
- Update cognite-sdk-scala so that it is using the `v1` version of the well data layer.
[WDL-1034]
[WDL-1034]: https://cognitedata.atlassian.net/browse/WDL-1034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WDL: add itemsCreated metric and upgrade to api-version v1

---

build.sbt
patch_version.txt

With `patch-version` file it is publishing a wrong version
https://github.com/cognitedata/cdp-spark-datasource/actions/runs/4698153321/jobs/8330098297
Same issue as in https://github.com/cognitedata/cognite-sdk-scala/pull/612

Remove patch version

---

src/main/scripts/Pipfile
src/main/scripts/Pipfile.lock

There are some dependabot security alerts about dependencies
used there and renovate bot can't update them, probably because
python 3.5 is EOL https://endoflife.date/python
Let's bump to 3.11

Bump python to 3.11 in src/main/scripts

---

build.sbt
src/main/scala/cognite/spark/v1/FlexibleDataModelCorePropertyRelation.scala
src/test/scala/cognite/spark/v1/FlexibleDataModelCorePropertyRelationTest.scala

These options were set in one of the two upsert functions to automatically create edge start and end nodes if they don't exist. Set them in the other function as well (which is called when a view reference is provided).

Auto create start and end nodes always

---

src/main/scala/cognite/spark/v1/FlexibleDataModelRelationFactory.scala
src/test/scala/cognite/spark/v1/FlexibleDataModelConnectionRelationTest.scala

[CDF-18991]
When looking for the matching property from `connectionPropertyName`, we failed to check that the found property is a property of the view indicated by `viewExternalId`. This would lead to a bug where the wrong property was picked if multiple views had properties of the same name.
[CDF-18991]: https://cognitedata.atlassian.net/browse/CDF-18991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix duplicate property bug

---

.github/workflows/main.yaml

Looks like that command is only defined at top-level project. It should still be ok to call it there as it shouldn't publish, only find what's published and release that
```
Error:  Not a valid key: sonatypeReleaseAll (similar: sonatypeLogLevel, sonatypeProfileName, sonatypeBundleClean)
Error:  +fatJar/sonatypeReleaseAll
```

Fixup sonatype publishall

---

build.sbt

Found similar issues in other repos, sbt-sonatype error message isn't very helpful
but it seems that profileName mismatch is the issue why it didn't find anything
to publish

one more sonatype publish fixup

---

src/main/scala/cognite/spark/v1/FlexibleDataModelCorePropertyRelation.scala
src/test/scala/cognite/spark/v1/FlexibleDataModelCorePropertyRelationTest.scala

If we don't see a property in the row for a node or edge, don't remove it. This amounts to setting `replace = false` in the sdk call.
We still don't handle nulls completely correctly: If `ignoreNullFields = false`, we ought to remove properties that are null in the row. But let's leave that for later - the first fix is more important to get out.
Also, we need to figure out what to do in the other class, `FlexibleDataModelConnectionRelation`. But that's also for later.

Fix: Leave unmentioned properties alone

---

renovate.json

Don't trigger automatic rebase of renovate pr unless there's a merge conflict.
This should stop CD from failing once we're merged because of CI overload.

Renovate: Less rebasing

---

.github/workflows/main.yaml
build.sbt

Depending on use-case, consuming pure library and extending it
could be more ergonomic than consuming fatjar library with
some dependencies shaded.

Publish non-shaded slim jar too

---

src/test/scala/cognite/spark/v1/DefaultSourceClassTest.scala

DefaultSource should have default constructor for
executors to be able to create it.

Add simple test about DefaultSource class

---

src/main/scala/cognite/spark/v1/CdfSparkAuth.scala
src/main/scala/cognite/spark/v1/DefaultSource.scala
src/test/scala/cognite/spark/v1/AssetHierarchyBuilderTest.scala
src/test/scala/cognite/spark/v1/SdkV1RddTest.scala

`maybeCacheToken` has a misleading name, it actually is only an
optional initial token which will be used until it expires
https://github.com/cognitedata/cognite-sdk-scala/blob/2c1e74e67b3eba42ca564f53af08021ba146c642/src/main/scala/com/cognite/sdk/scala/common/OAuth2.scala#L173
https://github.com/cognitedata/cognite-sdk-scala/blob/2c1e74e67b3eba42ca564f53af08021ba146c642/src/main/scala/com/cognite/sdk/scala/common/OAuth2.scala#L200
But after it expires or if it wasn't provided normal path would be
used to fetch a new token and persist it via `CachedResource` and
invalidate-refresh as needed in `commonGetAuth`
https://github.com/cognitedata/cognite-sdk-scala/blob/2c1e74e67b3eba42ca564f53af08021ba146c642/src/main/scala/com/cognite/sdk/scala/common/OAuth2.scala#L133
The intent is to be able …

Cleanup redundant maybeCacheToken

---

src/main/scala/cognite/spark/v1/DataModelInstancesRelation.scala
src/main/scala/cognite/spark/v1/NumericDataPointsRelation.scala
src/main/scala/cognite/spark/v1/SequenceRowsRelation.scala
src/main/scala/cognite/spark/v1/StringDataPointsRelation.scala

Seeing if method is doing an override or not is quite helpful when
doing refactorings. Those that do override have to be kept as is
or refactored along with the interface, while non-overriding ones
are safe to change in any suitable way.
Sadly didn't manage to persist a linter for this
- scalafix + https://github.com/xplosunn/ForceOverrides doesn't work
because that extension is outdated and not compatible with recent scalafix
- https://github.com/wartremover/wartremover-contrib#missingoverride
produces warning also for `val` overrides (that's ok) but also seemingly
some false positives at places that aren't even declarations but rather fn calls

Add some explicit override-s

---

src/main/scala/cognite/spark/v1/AssetsRelation.scala
src/main/scala/cognite/spark/v1/CdfRelation.scala
src/main/scala/cognite/spark/v1/DataSetsRelation.scala
src/main/scala/cognite/spark/v1/DefaultSource.scala
src/main/scala/cognite/spark/v1/EventsRelation.scala
src/main/scala/cognite/spark/v1/FilesRelation.scala
src/main/scala/cognite/spark/v1/LabelsRelation.scala
src/main/scala/cognite/spark/v1/RelationshipsRelation.scala
src/main/scala/cognite/spark/v1/SdkV1InsertableRelation.scala
src/main/scala/cognite/spark/v1/SdkV1Relation.scala
src/main/scala/cognite/spark/v1/SequencesRelation.scala
src/main/scala/cognite/spark/v1/TimeSeriesRelation.scala

OOP overrides hell consequences.
- `SdkV1Relation` was defining an `insert(data, overwrite)` method
but didn't extend spark's `InsertableRelation`
- `SdkV1Relation` was defining a by-default-throwing `getFromRowsAndCreate`
that is used by `insert` method above
- some subclasses were defining `getFromRowsAndCreate` and extending
`InsertableRelation` which would pick up `insert` method in a side-channel
manner from `SdkV1Relation` (no direct and simple way to see that that
`insert` was actually meant for `InsertableRelation`)
Let's move insertable part to a dedicated subclass which doesn't have unsafe
fallback and does inherit-override the insert method.
This will remove `InsertableRelation` interface from some of classes,
but only from those that were throwing on using it anyway.
TODO for …

Introduce SdkV1InsertableRelation subclass

---

src/main/scala/cognite/spark/v1/DefaultSource.scala
src/main/scala/cognite/spark/v1/PushdownUtilities.scala
src/test/scala/cognite/spark/v1/EventsRelationTest.scala
src/test/scala/cognite/spark/v1/SparkTest.scala

Substaintial rewrite of EventsRelationTest but it should
preserve most of its meaning.
- explicitly create all items used by test
- introduce extra helper methods and checks
- use randomized event.source for test scope isolation
- un-ignore ignored tests
- some tests may change slightly but intent is to keep
scenarios approximately the same
Extra notes:
- PushdownUtilities convert `> x` to `min(x)` aka `>= x` which
should ideally be changed to `min(succ(x))` but for later.
It seems that it doesn't lead to wrong results currently,
we pushdown broader than needed condition down but afterwards
spark still applies original exact filter
- adding SparkTest safe counter access which has fallback from
missing metric to 0 which is useful for retry conditions in tests
which shouldn't throw if …

CDF-19653: make EventsRelationTest less flaky

---

build.sbt

Currently
https://repo1.maven.org/maven2/com/cognite/spark/datasource/cdf-spark-datasource-fatjar_2.13/3.2.1044/cdf-spark-datasource-fatjar_2.13-3.2.1044.pom
includes
```xml
<dependencies>
<dependency>
<groupId>org.scala-lang</groupId>
<artifactId>scala-library</artifactId>
<version>2.13.8</version>
</dependency>
<dependency>
<groupId>com.cognite.spark.datasource</groupId>
<artifactId>cdf-spark-datasource_2.13</artifactId>
<version>3.2.1044</version>
</dependency>
<dependency>
<groupId>io.scalaland</groupId>
<artifactId>chimney_2.13</artifactId>
<version>0.5.3</version>
</dependency>
</dependencies>
```
Which isn't expected, fatjar should have (almost) no dependencies.
The jar itself though contains all the classes and applies shading
as expected.
It is then possible that pulling fatjar …

CDF-20156: fixup fatjar pom file

---

src/main/scala/cognite/spark/v1/FlexibleDataModelBaseRelation.scala

During scan we have deduplication of items, it was done by just `externalId`.
But `externalId` can be reused between different spaces in dms case.
So let's pass `space` around and use `space`+`externalId` for deduplication.
We do have `space` value available, just a matter of using it.
[CDF-20182]
[CDF-20182]: https://cognitedata.atlassian.net/browse/CDF-20182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CDF-20182: fix fdm deduplication logic: use (space, externalId) instead of just (space)

---

src/main/scala/cognite/spark/v1/AssetsRelation.scala
src/main/scala/cognite/spark/v1/DataSetsRelation.scala
src/main/scala/cognite/spark/v1/EventsRelation.scala
src/main/scala/cognite/spark/v1/FilesRelation.scala
src/main/scala/cognite/spark/v1/NumericDataPointsRelation.scala
src/main/scala/cognite/spark/v1/PushdownUtilities.scala
src/main/scala/cognite/spark/v1/RelationshipsRelation.scala
src/main/scala/cognite/spark/v1/StringDataPointsRelation.scala
src/main/scala/cognite/spark/v1/TimeSeriesRelation.scala
src/test/scala/cognite/spark/v1/PushdownUtilitiesTest.scala

Use Map,Seq,PushdownFilters of wasn't very readable and didn't express
semantics.
Let's use more explicit names like PushdownUnion or dedicated types to
wrap Map of and-ed simple filters and Seq of Or-ed filters.
No behavior changes expected.
Notes:
It might make sense to also avoid exposing Seq and rather have True + NonEmptySeq
cases to make forgetting that empty seq == true predicate and and-ing
it with others isn't same as combining each element. But for now
let's keep that part as-is.
Another thing to maybe look at later is generalizing/extracting the id/externalId
part as for example dms has space+externalId as primary identifier and some
resources don't special-case `id` (relationships). But for now it looks
safe enough - dms doesn't use pushdown utilities and relationships don't …

Prettify filter pushdown names&types

---

src/main/scala/cognite/spark/v1/FlexibleDataModelBaseRelation.scala

`externalId` is a special property and exists on `node`/`edge` rather than on
`space/versionedExternalId`.
There already was handling of that for `EqualTo` filters but was missing
for `In` and `Prefix` filters so let's extend this.
The code around here could definitely benefit from some refactoring, maybe
introducing dedicated types for various kinds of references etc.
But that needs more thought and for now mighty copy-paste it is.
[CDF-20199]
[CDF-20199]: https://cognitedata.atlassian.net/browse/CDF-20199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CDF-20199: fix dms externalId.{startswith,in} filters

---

src/test/scala/cognite/spark/v1/RawTableRelationTest.scala

Making the test create all the data it expects to exist so that it can be
run in any project.
Small change in behavior is `lastUpdatedTime` range test, ideally we should
be able to test that too, but we don't control the value when ingesting into
raw. So let's for now have slightly weaker test using `lastUpdatedTime(now) >= somewhere in the past`
and more strong test using range of `startTime`. Should be good enough for now,
plus there are other pushdown tests.
[CDF-20103]
[CDF-20103]: https://cognitedata.atlassian.net/browse/CDF-20103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CDF-20103: make RawTableRelationTest less flaky

---

build.sbt

Can lead to failure to run `sbt test` on `openjdk-17.0.6+10`
```
Unrecognized VM option 'CMSClassUnloadingEnabled'
```
Looks like it could only be useful for CMS garbage collector and
option got removed in jdk14+ along with CMS collector.

Remove CMSClassUnloadingEnabled from build.sbt

---

src/test/scala/cognite/spark/v1/FilesRelationTest.scala

Create all files (&labels) that test expects to see as part of test setup,
cleanup afterwards. Should make this test work in any project.
Changes are similar to EventRelationTest
Overall setup isn't super-pretty yet, but that's a task for another day.
For now it should fix tests in `master` and not depend on state of data in test project.
[CDF-20827]
[CDF-20827]: https://cognitedata.atlassian.net/browse/CDF-20827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CDF-20827: make FilesRelationTest less flaky

---

build.sbt
src/main/scala/cognite/spark/v1/CdpConnector.scala
src/main/scala/cognite/spark/v1/DefaultSource.scala
src/main/scala/cognite/spark/v1/FixedTraceSttpBackend.scala
src/main/scala/cognite/spark/v1/RelationConfig.scala
src/test/scala/cognite/spark/v1/SparkTest.scala

Adds bare minimum support for trace propagation
- no spans are created in connector itself
- no spans are created by SDK
- no new spans are exported
- no change of `IO` -> `Kleisli[IO, Span[IO], *]` or related changes
But already
- support passing parent span via job parameters
- pass that span on to SDK via headers
Full tracing support with spans created in datasource and exported
from spark workers remains a todo, there were some issues rolling
it out before as it had effect handling & type changes.
Just passing on the header should be safe enough.
Small concern is that we don't introduce spans per operation,
but the receiving end of SDK call would create a span of its
own, datasource would only be seen as proxy in traces ~ same as if
datasource creator would call SDK directly. …

CDF-20904: add simple trace propagation

---

src/main/scala/cognite/spark/v1/FlexibleDataModelCorePropertyRelation.scala

specific error reported here (https://cognitedata.slack.com/archives/C053BKT7TJ8/p1709579684024929)  happens on the deserialization path used when we do not request views
also [CDF-21080]
[CDF-21080]: https://cognitedata.atlassian.net/browse/CDF-21080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Request view data to go down on other deserialization path in SDK

---

build.sbt
build.scala-2.12.sbt.lock
build.scala-2.13.sbt.lock
macro/build.scala-2.12.sbt.lock
macro/build.scala-2.13.sbt.lock
src/main/scala/cognite/spark/v1/FlexibleDataModelCorePropertySyncRelation.scala
src/test/scala/cognite/spark/v1/FlexibleDataModelCorePropertyRelationTest.scala

General idea is to do syncing in two phases:
Phase 1: list out items with cursor on internal node id in DMS
Phase 2: sync out incremental changes that happened since phase 1
We will initialise a cursor for phase 1 when we start it.

Enable two-phase syncing to avoid 408

---

src/main/scala/cognite/spark/v1/DefaultSource.scala
src/main/scala/cognite/spark/v1/FlexibleDataModelCorePropertySyncRelation.scala
src/main/scala/cognite/spark/v1/FlexibleDataModelRelationFactory.scala
src/main/scala/cognite/spark/v1/SttpClientBackendFactory.scala
src/main/scala/cognite/spark/v1/SyncCursorCallback.scala

Currently, we return the cursor from the /sync DMS call as part of the rows returned to the Dataframe. This cursor has a max lifespan (currently 3 days), and needs to be refreshed even if there are no rows returned.
As a workaround, for now, we therefore submit the cursor to a configured callback URL when the /sync query returns no entries.

Submit last (empty) sync cursor to callback

---

src/test/scala/cognite/spark/v1/SequenceRowsRelationTest.scala

apparently it is making conflicts for itself, leading to the test taking 25+ minutes (!).

Avoid ParallelTestExecution for sequences

---

src/main/scala/cognite/spark/v1/SdkV1Relation.scala

36b9900c83d795d04689136e4474458fb937b19d introduced it when doing some other change,
it doesn't look like setting `externalId` to `None` is the intent in that code either before or in the change.
One of library maintainers mentioned it in
https://github.com/cognitedata/cdp-spark-datasource/pull/933/files#r1611561212
and that it will be rejected in newer library versions.
Let's make this change in isolation to make update to `1.0.0` more clean

Cleanup unused withFieldComputed

---

build.sbt
src/main/scala/cognite/spark/v1/CdfRelation.scala
src/main/scala/cognite/spark/v1/CdpConnector.scala
src/main/scala/cognite/spark/v1/MetricsSource.scala
src/main/scala/cognite/spark/v1/RawTableRelation.scala
src/test/scala/cognite/spark/v1/EventsRelationTest.scala
src/test/scala/cognite/spark/v1/MetricsSourceTest.scala
src/test/scala/cognite/spark/v1/RawTableRelationTest.scala
src/test/scala/cognite/spark/v1/SparkTest.scala
src/test/scala/cognite/spark/v1/TimeSeriesRelationTest.scala

By adding the attempt number to the metrics it will be possible to get
the highest attempt for each stage and task and allowing ignoring
metrics coming from failed/retried tasks. A good example would be the
effective number of rows added.
Though, the metrics don't allow labels, and instead uses dot-delimited
fields such as job id.
By keeping always a consistent number of fields, these can be extracted
while aggregating the metrics. Therefore, it is the responsibility of
the MetricSource to enforce this consistency.

Celo/cdf 21249/attempt number metrics

---

src/main/scala/cognite/spark/v1/CdfRelation.scala
src/main/scala/cognite/spark/v1/CdpConnector.scala
src/main/scala/cognite/spark/v1/DefaultSource.scala
src/main/scala/cognite/spark/v1/MetricsSource.scala
src/main/scala/cognite/spark/v1/RawTableRelation.scala
src/main/scala/cognite/spark/v1/RelationConfig.scala
src/test/scala/cognite/spark/v1/DefaultSourceTest.scala
src/test/scala/cognite/spark/v1/SparkTest.scala

Let the driver control the attempt tracking of metrics
Will default to `false`

Control attempt tracking from config

---

src/main/scala/cognite/spark/v1/FlexibleDataModelBaseRelation.scala
src/main/scala/cognite/spark/v1/FlexibleDataModelConnectionRelation.scala
src/main/scala/cognite/spark/v1/FlexibleDataModelCorePropertyRelation.scala
src/main/scala/cognite/spark/v1/FlexibleDataModelCorePropertySyncRelation.scala
src/test/scala/cognite/spark/v1/FlexibleDataModelCorePropertyRelationTest.scala

So there were always two cases:
* filter on reserved keywords
* filter on normal view attributes
They were handled somewhat separately, but the entire code for filtering on reserved keywords was repeated. Similarly, the code for combined filter (not, and, or etc...) was repeated too.
This makes it so there is a single filter function with optional view version and space, which will check if the attribute is a reserved keyword and if so will use the filter on reserved keyword, if not will filter on view attributes.
This enables some cleanup in other parts as well, where these two were chained.
Some more cleanup was done to avoid having to individually check each attributes, and instead handle them together (while keeping in mind some are string attributes and others are references)
It's …

Improve filters

---

src/main/scala/cognite/spark/v1/FlexibleDataModelCorePropertyRelation.scala
src/main/scala/cognite/spark/v1/FlexibleDataModelRelationUtils.scala
src/test/scala/cognite/spark/v1/FlexibleDataModelRelationUtilsTest.scala

This PR proposes removing a duplicate flow for empty sources.
Currently we handle the situations where sources are empty (writing a node/edge as a standalone, not referencing any view) and the situations where we are writing the instance to a view completely separately, with method overload.
This proposes removing the separated flow, and handling it together, with the sources being optional.
Advantages:
* removal of redundant code
* easier to maintain (only have to maintain one flow)
* relatively straightforward handling of None when sources are empty
The price is that it's very slightly more complex and if we want to make more code specific to one situation in the future we might have to duplicate some parts again.
Reasoning for doing this now:
* Edge property support is coming soon, and …

remove duplication in createNodeOrEdge

---

src/main/scala/cognite/spark/v1/fdm/FlexibleDataModelBaseRelation.scala
src/test/scala/cognite/spark/v1/fdm/FlexibleDataModelNodeTest.scala

fixes: https://cognitedata.atlassian.net/browse/CDF-22435
Looks like the "in" filter is broken in various ways, and in general toFilterValueListDefinition which also means = on lists was broken.
Examples of broken requests before and after:
```
select
cast(`externalId` as STRING) as externalId,
cast(`code` as STRING) as code
from
cdf_data_models("spaaace", "test_in_number_bug", "1", "Facility2")
where code in ("1", "2")
```
This would map the array into an array of int. It would get picked up as a Json, thus serialized as a json value which would be 1 not "1" as expected.
```
select
cast(`externalId` as STRING) as externalId,
cast(`code` as STRING) as code
from
cdf_data_models("spaaace", "test_in_number_bug", "1", "Facility2")
where code in (1, 2)
```
This wouldn't work at all. It would …

fix in filter

---

README.md
build.sbt
build.scala-2.12.sbt.lock
build.scala-2.13.sbt.lock
macro/build.scala-2.12.sbt.lock
macro/build.scala-2.13.sbt.lock
src/main/scala/cognite/spark/v1/DefaultSource.scala
src/main/scala/cognite/spark/v1/RawTableRelation.scala
src/main/scala/cognite/spark/v1/RelationConfig.scala
src/test/scala/cognite/spark/v1/RawTableRelationTest.scala
src/test/scala/cognite/spark/v1/SparkTest.scala

This change exposes the Raw-API support for filtering nulls server side through the cdp data source. It does not impact schema interference, as that is still done without filtering.

Support optional filtering of null values from RAW

---

src/main/scala/cognite/spark/v1/AssetsRelation.scala
src/main/scala/cognite/spark/v1/DataSetsRelation.scala
src/main/scala/cognite/spark/v1/EventsRelation.scala
src/main/scala/cognite/spark/v1/FilesRelation.scala
src/main/scala/cognite/spark/v1/RelationSchemas.scala
src/main/scala/cognite/spark/v1/RelationshipsRelation.scala
src/main/scala/cognite/spark/v1/TimeSeriesRelation.scala
src/test/scala/cognite/spark/v1/SttpClientBackendFactoryTest.scala

initialization order means this system of updateSchemaFromUpsertSchema didn't work unfortunately
In practice update schema will be null.

fix update schema

---

src/main/scala/cognite/spark/v1/FileContentRelation.scala
src/test/scala/cognite/spark/v1/FileContentRelationTest.scala

Seems like uploading a file through fusion with .ndjson extension will automatically set some different mimetype. Let's just remove this.

Remove mimetype check

---

build.sbt
src/main/scala/cognite/spark/v1/SequencesRelation.scala

sequences should support update

---

src/main/scala/cognite/spark/v1/FileContentRelation.scala
src/test/scala/cognite/spark/v1/FileContentRelationTest.scala

There is a debate between using byte size and character size.
This is my preferred approach because:
* while it's easy for a customer to check the byte size of a file, it's less straightforwards with a line, because it depends on encoding, and the file won't report it to them directly.
* it avoids unnecessary processing and uses ready-made fs2 methods
here is a draft of the alternative to give you an idea of what the flow would be like:
https://github.com/cognitedata/cdp-spark-datasource/pull/995
(not if the alternative is preferred, the processing code needs a heavy coat of cleanup but the main idea is there)

Character line size limit

---

.github/workflows/main.yaml

Looks like something has changed and https://github.com/coursier/setup-action/ installing `sbtn` no longer installed `sbt` binary.
Let's pin action version for more explicit upgrades, and install `sbt` instead of `sbtn` to hopefully fix the build.
Without it build fail with
```
Run sbt -Dsbt.log.noformat=true +{,macroSub/,structType/}dependencyLockCheck
/home/runner/work/_temp/a737f15b-e7ab-4208-ba7f-f620b1b062d2.sh: line 1: sbt: command not found
Error: Process completed with exit code 127.
```

Pin coursier/setup-action by full version, sbtn->sbt to try fix the build

---

src/main/scala/cognite/spark/v1/FileContentRelation.scala

Since filecontent doesn't go through `SdkV1Relation.{buildScan, getStream}` to implement reads
read metrics weren't being automatically reported.
Now it will do `itemsRead.inc()` once per line

filecontent: report itemsRead metric

---

src/main/scala/cognite/spark/v1/SyncCursorCallback.scala
src/test/scala/cognite/spark/v1/SyncCursorCallbackTest.scala

We used to only handle non-OK responses from `jetfire-backend`, meaning that connection errors such as timeouts or connection refused would throw and be unhandled
Examples:
* https://jetfire-admin.iap.az-eastus-1.cognite.dev/jobs/filter?uuid=6f5ca314-e0c4-4ee3-95d7-8e8064f95a18
* https://jetfire-admin.iap.az-eastus-1.cognite.dev/jobs/filter?uuid=bc4d6305-142a-4703-ad9e-721e38a9d840
* https://jetfire-admin.iap.az-eastus-1.cognite.dev/jobs/filter?uuid=0fc73d32-4466-4005-b78e-e0cfe30a8744

Handle connection error on cursor update

---

src/main/scala/cognite/spark/v1/DefaultSource.scala

Notes:
- doesn't cover `NumericDataPointsRdd`, `StringDataPointsRdd` and `FileContentRelation`
- for `SdkV1Rdd` doesn't cover cases where `getStreams` returns fewer
than `config.sparkPartitions`, for such cases logger value is `config.sparkPartitions`
rather than `getStreams` length
- we could also add metrics, but then it probably needs to be a histogram
and so may need a little more thought for implementation

Add some logging for partition settings

---

src/test/scala/cognite/spark/v1/fdm/FlexibleDataModelSyncTest.scala

Test currently fails with
```
[info]   com.cognite.sdk.scala.common.CdpApiException: Request with id 54a37b91-6d30-97c6-86f4-75c56c4c72c5 to https://bluefield.cognitedata.com/api/v1/projects/extractor-bluefield-testing/models/instances/sync failed with status 500: Internal server error. Please report this error to support@cognite.com and provide us with your request id: 54a37b91-6d30-97c6-86f4-75c56c4c72c5 and cluster name: bluefield.
```
but internally it seems more like 400 (cursor format changed or cursor is way too old?)

FlexibleDataModelSyncTest: ignore broken test
