cognitedata/cdp-spark-datasource

src/main/scala/com/cognite/spark/datasource/DataPointsRelation.scala

Please ignore if this was left out intentionally.

Report datapoints.read metrics

---

build.sbt

Let me know if you'd like to be added to the list of developers, it's a required field so it needs to be set to something, but I don't want it to look like I'm trying to take all the credit. ;)

Add developers metadata required by OSSRH Sonatype repository

---

README.md
src/main/scala/com/cognite/spark/datasource/DataPointsRelation.scala
src/test/scala/com/cognite/spark/datasource/DataPointsRelationTest.scala

TODO: Add a test, since this really should have been caught by a test before being shipped.

Fix posting of data points

---

src/main/scala/com/cognite/spark/datasource/AssetsRelation.scala
src/main/scala/com/cognite/spark/datasource/CdpConnector.scala
src/main/scala/com/cognite/spark/datasource/EventsRelation.scala
src/main/scala/com/cognite/spark/datasource/FilesRelation.scala
src/main/scala/com/cognite/spark/datasource/ThreeDModelRevisionMappingsRelation.scala
src/main/scala/com/cognite/spark/datasource/ThreeDModelRevisionNodesRelation.scala
src/main/scala/com/cognite/spark/datasource/ThreeDModelRevisionSectorsRelation.scala
src/main/scala/com/cognite/spark/datasource/ThreeDModelRevisionsRelation.scala
src/main/scala/com/cognite/spark/datasource/ThreeDModelsRelation.scala
src/main/scala/com/cognite/spark/datasource/TimeSeriesRelation.scala
src/test/scala/com/cognite/spark/datasource/BasicUseTest.scala
src/test/scala/com/cognite/spark/datasource/SparkTest.scala
src/test/scala/com/cognite/spark/datasource/TimeSeriesUpsertTest.scala

Tests are still not 100% stable wrt. eventual consistency.

Enable upsert of time series

---

src/main/scala/com/cognite/spark/datasource/EventsRelation.scala

Id, createdTime and lastUpdatedTime should no longer be specified when
creating a new Event, so remove these from the Posts when creating new
Events.

Remove deprecated fields from create Events

---

README.md
src/main/scala/com/cognite/spark/datasource/FilesRelation.scala
src/main/scripts/createFilesMetadata.py
src/main/scripts/testfile.txt
src/test/scala/com/cognite/spark/datasource/FilesRelationTest.scala

I've added update for Files metadata, but not insert. Uploading new files requires user action for each new file within 30 seconds: https://doc.cognitedata.com/api/0.6/#operation/initiateUploadSession

Add update for Files metadata

---

src/main/scala/com/cognite/spark/datasource/AssetsRelation.scala
src/main/scala/com/cognite/spark/datasource/CdpConnector.scala
src/main/scala/com/cognite/spark/datasource/Constants.scala
src/main/scala/com/cognite/spark/datasource/DataPointsRdd.scala
src/main/scala/com/cognite/spark/datasource/DataPointsRelation.scala
src/main/scala/com/cognite/spark/datasource/DefaultSource.scala
src/main/scala/com/cognite/spark/datasource/EventsRelation.scala
src/main/scala/com/cognite/spark/datasource/FilesRelation.scala
src/main/scala/com/cognite/spark/datasource/NumericDataPointsRdd.scala
src/main/scala/com/cognite/spark/datasource/NumericDataPointsRelation.scala
src/main/scala/com/cognite/spark/datasource/RawTableRelation.scala
src/main/scala/com/cognite/spark/datasource/StringDataPointsRdd.scala
src/main/scala/com/cognite/spark/datasource/StringDataPointsRelation.scala
src/main/scala/com/cognite/spark/datasource/TimeSeriesRelation.scala
src/test/scala/com/cognite/spark/datasource/DataPointsRddTest.scala

Let DataPointsRdd handle multiple time series, avoid DataFrame union

---

src/main/scala/com/cognite/spark/datasource/DataPointsRelation.scala

Fixes https://github.com/cognitedata/cdp-spark-datasource/issues/253

Use the baseUrl option in DataPointsRelation

---

README.md

Add a table of contents to the README for easier navigation and overview.

Add readme table of contents and restructure

---

src/main/scala/com/cognite/spark/datasource/Constants.scala
src/main/scala/com/cognite/spark/datasource/RawTableRelation.scala
src/test/scala/com/cognite/spark/datasource/RawTableRelationTest.scala
src/test/scala/com/cognite/spark/datasource/SparkTest.scala

Inferschema limit was before ignored, now it's enabled again.

Use inferschema limit

---

src/main/scala/com/cognite/spark/datasource/DataPointsRelation.scala
src/main/scala/com/cognite/spark/datasource/RawTableRelation.scala
src/test/scala/com/cognite/spark/datasource/RawTableRelationTest.scala

Add push down filter for raw lastChanged

---

src/main/scala/com/cognite/spark/datasource/AssetsRelation.scala
src/main/scala/com/cognite/spark/datasource/CdpRelation.scala
src/main/scala/com/cognite/spark/datasource/EventsRelation.scala
src/main/scala/com/cognite/spark/datasource/TimeSeriesRelation.scala

This feature can be used by Jetfire to retrieve the right schema based on save mode, when Jetfire gets support for it.

Expose struct type schema

---

src/main/scala/com/cognite/spark/datasource/AssetsRelation.scala
src/main/scala/com/cognite/spark/datasource/EventsRelation.scala
src/test/scala/com/cognite/spark/datasource/AssetsRelationTest.scala

Assets will now do upsert when the source+sourceId already exists.

Implement upserts for Assets

---

src/test/scala/com/cognite/spark/datasource/AssetsRelationTest.scala
src/test/scala/com/cognite/spark/datasource/DataPointsRelationTest.scala
src/test/scala/com/cognite/spark/datasource/EventsRelationTest.scala

There has been some sudden braking changes in the API which crashes our tests.
This commit fixes those tests.

Fix broken tests

---

src/main/scala/com/cognite/spark/datasource/CdpConnector.scala
src/main/scala/com/cognite/spark/datasource/CdpEventsRdd.scala
src/main/scala/com/cognite/spark/datasource/CdpRelation.scala
src/main/scala/com/cognite/spark/datasource/EventsRelation.scala
src/test/scala/com/cognite/spark/datasource/EventsRelationTest.scala

Pushdown on event ids now uses the "events/byids" endpoint and makes a post request with the ids in the body. Currently writing more tests.

Add pushdown on event id

---

src/main/scala/com/cognite/spark/datasource/CdpRelation.scala
src/main/scala/com/cognite/spark/datasource/EventsRelation.scala
src/test/scala/com/cognite/spark/datasource/AssetsRelationTest.scala
src/test/scala/com/cognite/spark/datasource/CdpRelationTest.scala
src/test/scala/com/cognite/spark/datasource/EventsRelationTest.scala

Currently breaks events.
(edit) not any more

Optimize pushdown

---

src/main/scala/cognite/spark/CdpRelation.scala
src/main/scala/cognite/spark/EventsRelation.scala
src/main/scala/cognite/spark/TimeSeriesRelation.scala
src/test/scala/cognite/spark/DataPointsRelationTest.scala
src/test/scala/cognite/spark/TimeSeriesRelationTest.scala

Pushdown filters on assetId for Time Series.

Pushdown filters timeseries

---

build.sbt
src/main/scala/cognite/spark/v1/AssetsRelation.scala
src/main/scala/cognite/spark/v1/EventsRelation.scala
src/main/scala/cognite/spark/v1/PushdownUtilities.scala
src/main/scala/cognite/spark/v1/SdkV1Relation.scala
src/main/scala/cognite/spark/v1/TimeSeriesRelation.scala
src/test/scala/cognite/spark/v1/AssetsRelationTest.scala
src/test/scala/cognite/spark/v1/EventsRelationTest.scala
src/test/scala/cognite/spark/v1/TimeSeriesRelationTest.scala

-- Update the spark datasource to use updatebyId() and updateByExternalId() from the scala sdk
-- Test that we can update resources by specifying externalId

Update update logic

---

src/test/scala/cognite/spark/v1/FilesRelationTest.scala

Files update is struggling with slow Elastic Search results. This uses the SDK filtering method, and runs a lot faster.

Speed up files test by filtering with SDK

---

src/main/scala/cognite/spark/v1/AssetHierarchyBuilder.scala
src/main/scala/cognite/spark/v1/CdfRelation.scala
src/main/scala/cognite/spark/v1/SdkV1Relation.scala
src/main/scala/cognite/spark/v1/TimeSeriesRelation.scala
src/test/scala/cognite/spark/v1/AssetHierarchyBuilderTest.scala
src/test/scala/cognite/spark/v1/AssetsRelationTest.scala
src/test/scala/cognite/spark/v1/EventsRelationTest.scala
src/test/scala/cognite/spark/v1/SparkTest.scala

Adds metrics for delete operations.

[DT-1255] Delete metrics

---

src/main/scala/cognite/spark/v1/AssetsRelation.scala
src/main/scala/cognite/spark/v1/EventsRelation.scala
src/main/scala/cognite/spark/v1/SdkV1Relation.scala
src/main/scala/cognite/spark/v1/TimeSeriesRelation.scala
src/test/scala/cognite/spark/v1/TimeSeriesRelationTest.scala

This fixes a bug, where only some updated items have non-null fields.

[DT-900] Add support for empty updates

---

README.md
src/main/scala/cognite/spark/v1/NumericDataPointsRdd.scala
src/test/scala/cognite/spark/v1/DataPointsRelationTest.scala
src/test/scala/cognite/spark/v1/EventsRelationTest.scala

All datapoints weren't read if there were less than 10,000 datapoints per 300 days in some interval.

[DT-1417] Fix sparse datapoints error

---

src/main/scala/cognite/spark/v1/Constants.scala
src/main/scala/cognite/spark/v1/DataPointsRelation.scala
src/main/scala/cognite/spark/v1/DefaultSource.scala

Before this we were only writing batches of 1,000 data points. This will increase this to 10,000 data points.

Increase number of data points to write per batch

---

macro/src/main/scala/SparkSchemaHelper.scala
src/test/scala/cognite/spark/v1/DataPointsRelationTest.scala

Before this change, Spark failed with message like "failed due to missing value column",
when the type was not matching the expected one, or the value was null.
Now it prints which column has invalid type and also on which row the error occurs

[DT-1275] Improve error message for column with invalid type or missing value

---

Jenkinsfile

https://github.com/cognitedata/docker-sbt/pull/1 changed the image name in the repository

Use current Docker registry images

---

Jenkinsfile

The test failures will then be easier accessible through the Jenkins UI.

Report test failures to Jenkins

---

src/main/scala/cognite/spark/v1/PushdownUtilities.scala
src/test/scala/cognite/spark/v1/AssetsRelationTest.scala

Fixes queries like `where X in (null, "a", "b")` + I have added tests and asserts for other operators when using NULLs

[DT-1118]Fix null handling in filter pushdown

---

build.sbt

We will need this for exception handling in jetfire.

Bump Scala SdK version

---

src/main/scala/cognite/spark/v1/StreamIterator.scala

Stops spark-shell from hanging on :quit

Use daemon threads for StreamIterator's "drain" thread pool

---

src/main/scala/cognite/spark/v1/AssetHierarchyBuilder.scala
src/test/scala/cognite/spark/v1/AssetHierarchyBuilderTest.scala

Feel free to pick this up if you have the time @wjoel 
Seems to be working, but the test takes ages so I'm probably doing something stupid with the traversal here

[WIP] Do batching of asset subtrees

---

src/main/scala/cognite/spark/v1/NumericDataPointsRdd.scala
src/main/scala/cognite/spark/v1/StringDataPointsRelation.scala
src/test/scala/cognite/spark/v1/DataPointsRelationTest.scala
src/test/scala/cognite/spark/v1/StringDataPointsRelationTest.scala

Previously this resulted in a circe error being produced or no
error in some cases.

Nice error: reading string -> numeric datapoints

---

CHANGELOG.md
src/main/scala/cognite/spark/v1/CdpConnector.scala
src/main/scala/cognite/spark/v1/MetricsBackend.scala
src/main/scala/cognite/spark/v1/RateLimitingBackend.scala
src/test/scala/cognite/spark/v1/AssetHierarchyBuilderTest.scala
src/test/scala/cognite/spark/v1/SparkTest.scala

Add RateLimitingBackend and metrics for num of requests

---

build.sbt
src/main/scala/cognite/spark/v1/CdfSparkAuth.scala
src/main/scala/cognite/spark/v1/DefaultSource.scala
src/main/scala/cognite/spark/v1/SdkV1Relation.scala
src/test/scala/cognite/spark/v1/DefaultSourceTest.scala

Add Session as auth type

---

CHANGELOG.md
build.sbt
src/main/scala/cognite/spark/v1/DefaultSource.scala
src/test/scala/cognite/spark/v1/DefaultSourceTest.scala

Add new field sessionId into Session

---

CHANGELOG.md
build.sbt
src/main/scala/cognite/spark/v1/DefaultSource.scala
src/test/scala/cognite/spark/v1/DefaultSourceTest.scala

CDF-14063
Go together with https://github.com/cognitedata/cognite-sdk-scala/pull/432

Add baseUrl into OAuth2.Session

---

.github/workflows/main.yaml
build.sbt

- Publish `fatJar` 
- Based on https://github.com/cognitedata/cdp-spark-datasource/commit/50186afb81f99a16777ed35304d80e7dd52485f1 and `sbt-assembly` 1.x [documentation](https://github.com/sbt/sbt-assembly#publishing-not-recommended).

publish fatjar settings

---

build.sbt

- extend from `commonSettings`

inherit commonSettings for fatJar

---

build.sbt

- shade jawn with full package to fix classNotFound issue in jetfire test

shade typelevel.jawn to fix classNotFound issue in jetfire

---

build.sbt

- remove `SNAPSHOT`
- correct naming mistake by renaming`cdp` to `cdf`

Final changes cdp-spark-datasource fatJar

---

src/test/scala/cognite/spark/v1/RawTableRelationTest.scala

Test for the hotfix in 26c2caf7d8be004cbf3e60ae86671ba0010a78d8

RAW: Add test for empty strings in numeric column

---

cdf_dump/README.md

Yea, markdown links... :facepalm:

Fix cdf_dump README

---

src/test/scala/cognite/spark/v1/RawTableRelationTest.scala

- Some how I managed to delete some tests. Adding them back.

Add unintentionally removed test

---

src/main/scala/cognite/spark/v1/DataModelInstancesRelation.scala
src/main/scala/cognite/spark/v1/DefaultSource.scala
src/test/scala/cognite/spark/v1/DataModelInstancesRelationTest.scala

Rename datamodelinstances as alphadatamodelinstances.

---

CHANGELOG.md
build.sbt

https://github.com/cognitedata/cognite-sdk-scala/commit/10375f9579ba9b570ff9f7ad85e0df8c1a7be481

Bump sdk to 2.3.4

---

build.sbt
src/main/scala/cognite/spark/v1/DataModelInstancesHelper.scala
src/test/scala/cognite/spark/v1/DataModelInstancesRelationTest.scala

CDF-17295
To be merged after https://github.com/cognitedata/cognite-sdk-scala/pull/581

Encode property Json as Json object not raw string

---

build.sbt
src/test/scala/cognite/spark/v1/DataModelInstancesRelationTest.scala

Follow up of https://github.com/cognitedata/cognite-sdk-scala/pull/583

Bump scala sdk to version to 2.4.4

---

src/main/scala/cognite/spark/v1/DefaultSource.scala
src/main/scala/cognite/spark/v1/FlexibleDataModelsRelation.scala

`instanceSpaceExternalId` is only required for upserting data

Make instanceSpaceExternalId optional

---

src/main/scala/cognite/spark/v1/FlexibleDataModelRelationUtils.scala
src/test/scala/cognite/spark/v1/FlexibleDataModelRelationUtilsTest.scala

- for string property types, accept any valid string convertible value
- handle java.sql.timestamps & java.sql.date types for timestamps and dates

Parse any value to string & Handle java.sql Date, timestamps

---

build.sbt
src/main/scala/cognite/spark/v1/FlexibleDataModelsRelation.scala
src/test/scala/cognite/spark/v1/FlexibleDataModelsRelationTest.scala

Changes for https://github.com/cognitedata/cognite-sdk-scala/pull/594

FDM api changes

---

src/main/scala/cognite/spark/v1/DefaultSource.scala
src/test/scala/cognite/spark/v1/SparkTest.scala

Repartitioning in the jetfire-backend instead.

Remove `maxWritePartitions`

---

README.md

Schemas - > Nodes
Schemas - Edges
Examples by resource types -> Nodes  (read and write) 
Examples by resource types -> Edges (read)

Update README.md with nodes and edges

---

README.md

-  - [View centric](#view-centric)
- [Nodes schema with view](#nodes-schema-with-view)
- [Nodes schema without view](#nodes-schema-without-view)
- [Edges schema with view](#edges-schema-with-view)
- [Edges schema without view (aka connection definition)](#edges-schema-without-view-aka-connection-definition)
- [Model centric](#model-centric)
- [Instances schema of type](#instances-schema-of-type)
- [Instances schema of relationship](#instances-schema-of-relationship)
- Instances to a type Example for read and write
-  Instances to a relationship for read and write
All the examples are tested and documented.  The result is dump here https://docs.google.com/document/d/1RJqEA0zHG2mfGPE8tL7vRyuxU7So2XrSt9qQ9iaEq7s/edit#heading=h.43pn0nfs3600

Update README.md with destination type Instances

---

.github/workflows/main.yaml

The setup-scala action is deprecated

Port from setup-scala to coursier/setup-action

---

src/main/scala/cognite/spark/v1/CdfPartition.scala
src/main/scala/cognite/spark/v1/CdpConnector.scala
src/main/scala/cognite/spark/v1/DefaultSource.scala
src/main/scala/cognite/spark/v1/RelationConfig.scala
src/main/scala/cognite/spark/v1/SdkV1Rdd.scala
src/main/scala/cognite/spark/v1/SdkV1Relation.scala
src/main/scala/cognite/spark/v1/WritableRelation.scala

Also remove more unused dto classes.
No changes semantically

Extract some classes to their own source files

---

build.sbt
src/main/scala/cognite/spark/v1/CdpConnector.scala
src/main/scala/cognite/spark/v1/MetricsBackend.scala

[CDF-19461]
[CDF-19461]: https://cognitedata.atlassian.net/browse/CDF-19461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CDF-19461: add request-response metrics per cdf resource type

---

src/main/scala/cognite/spark/v1/StreamIterator.scala

With some unrelated changes it was possible to make unit tests apparently
being stuck. Long story short
```scala
def getNextChunk(i: Iterator[A]): F[Option[(Chunk[A], Iterator[A])]] =
F.suspend(hint) {
for (_ <- 1 to chunkSize if i.hasNext) yield i.next()
}.map { s =>
if (s.isEmpty) None else Some((Chunk.from(s), i))
}
```
in fs2 streams was calling `StreamIterator.hasNext` thousands of times
even after putOnQueue has completed and we're done reading from queue too.
The issue is the combination of several things
- fs2 keeps calling `.hasNext` even after it returned `false` once
- `StreamIterator.hasNext` having waiting path even under `f.isComplete`
condition
- `StreamIterator` doing `ArrayBlockingQueue.poll()` with no timeout
and only relying on explicit Thread interrupts or spurious …

Improve StreamIterator wait/poll times

---

build.sbt

[CDF-19782]
[CDF-19782]: https://cognitedata.atlassian.net/browse/CDF-19782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CDF-19782: bump spark to 3.3.3

---

src/test/scala/cognite/spark/v1/ThreeDModelRevisionNodesRelationTest.scala

https://cognitedata.slack.com/archives/C85QG3UBU/p1695887877575709
https://github.com/cognitedata/service-contracts/pull/2313

Fixup 3d test - only pick a processed model for test

---

build.sbt
src/main/scala/cognite/spark/v1/SequencesRelation.scala

Compilation would fail until https://github.com/cognitedata/cognite-sdk-scala/pull/707 is in
[CDF-20229]
[CDF-20229]: https://cognitedata.atlassian.net/browse/CDF-20229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CDF-20229: add externalId filter pushdown to sequences

---

build.sbt
build.scala-2.12.sbt.lock
build.scala-2.13.sbt.lock
macro/build.scala-2.12.sbt.lock
macro/build.scala-2.13.sbt.lock
src/main/scala/cognite/spark/v1/FlexibleDataModelCorePropertySyncRelation.scala

- Ensures correct deserialisation if strings with dates, empty arrays, arrays with dates etc.
- Bumped to latest SDK version

Request inlined views in sync queries

---

.github/workflows/main.yaml

context: lately the pipeline for publish has been flaky (due to issue with sonatype) this PR will make it possible to rerun it without running the tests again (provided that the tests passed).

Split workflow publish

---

.github/workflows/main.yaml
build.sbt

[CDF-22158]
[CDF-22158]: https://cognitedata.atlassian.net/browse/CDF-22158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CDF-22158: dual-publish to jfrog & sonatype

---

src/main/scala/cognite/spark/v1/AssetsRelation.scala
src/main/scala/cognite/spark/v1/DataSetsRelation.scala
src/main/scala/cognite/spark/v1/EventsRelation.scala
src/main/scala/cognite/spark/v1/FilesRelation.scala
src/main/scala/cognite/spark/v1/SequencesRelation.scala
src/main/scala/cognite/spark/v1/TimeSeriesRelation.scala

Seems I'm not the only person doing this typo ^^

extenalId renamed to externalId

---

src/main/scala/cognite/spark/v1/FileContentRelation.scala
src/main/scala/cognite/spark/v1/SttpClientBackendFactory.scala

Doc is setting inf to duration... Let's do the same.
https://sttp.softwaremill.com/en/v2.0.0-rc9/backends/fs2.html

read timeeout duration inf

---

.github/workflows/main.yaml

I approved and merged your PR but we both missed that only 2/3 places had this change

add apps: sbt for sonatype too

---

src/main/scala/cognite/spark/v1/CdpConnector.scala

This should reduce chances of hitting a deadlock where all compute
threads are hitting class initialization lock that in turn wants
to run `.unsafeRunSync()` and needs a free compute thread to do that.
We may still get class initialization lock hits inside compute pool
which isn't great, but should only happen once per class and with this
fix hopefully won't lead to a deadlock as we now use unbounded blocking pool.
There doesn't seem to be other static class initialization using `.unsafeRunSync()`,
only calls to it from datasource implementation methods on non-effects <> cats-effect
boundary which we don't control because spark doesn't provide cats-effect interface.

Static initialization: unsafeRunSync -> evalOn(blocking).unsafeRunSync

---

build.sbt
build.scala-2.12.sbt.lock
build.scala-2.13.sbt.lock
macro/build.scala-2.12.sbt.lock
macro/build.scala-2.13.sbt.lock
src/main/scala/cognite/spark/v1/CdfRelation.scala
src/main/scala/cognite/spark/v1/fdm/FlexibleDataModelConnectionRelation.scala
src/main/scala/cognite/spark/v1/fdm/FlexibleDataModelCorePropertyRelation.scala

- bump sdk to get access to .wasModified response field
- add metric for dms noop write counts

count dms noop writes

---

src/main/scala/cognite/spark/v1/RawTableRelation.scala

With `maxOutstandingRawInsertRequests` parameter set we limit how many
RAW write request can be pending in parallel, this is both to limit
concurrency of writes, and to limit how many write request bodies
are prepared in memory (too many may lead to OOM)
Previously plain cats-effect was used, grouping into batches and running
each batch content in parallel.
Using fs2 Stream has couple improvements
- using Stream concurrency limit we can now utilize parallelism
continuosly instead of spiking to max allowed and then waiting for
batch to complete before adding more
- fromIterator instead of toVector won't also pull everything from
iterator eagerly which should save even more memory

RawTableRelation: use fs2 Stream to do parallel but limited RAW inserts
